# Generated by Django 5.1.2 on 2024-11-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('consultation', 'consultation'), ('message', 'Message'), ('session_start', 'Session_start'), ('session_stop', 'Session_stop')], max_length=50),
        ),
    ]
