# Generated by Django 5.1.2 on 2024-11-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-created_at',)},
        ),
    ]
