# Generated by Django 5.1.2 on 2024-11-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_active',
        ),
    ]
