# Generated by Django 5.1.2 on 2024-11-01 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_options_appointment_created_for_and_more'),
        ('consultations', '0002_alter_consultation_options_consultation_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.appointment'),
        ),
    ]
