# Generated by Django 5.1.2 on 2024-11-14 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_remove_doctorsessionmessage_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsession',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultations.consultation'),
        ),
    ]
