# Generated by Django 5.1.2 on 2024-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
