# Generated by Django 5.1.2 on 2024-11-17 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_doctorsessionmessage_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medications',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
