# Generated by Django 5.1.2 on 2024-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_allergies_user_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
