# Generated by Django 5.1.2 on 2024-11-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_notification_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_count',
        ),
    ]
