# Generated by Django 5.1.2 on 2024-12-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_notification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
